<a href="https://colab.research.google.com/github/AynSiddiqui/MyPharmacy/blob/ML/Drug_Recommendation_Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving pharmaceutical_drugs_dataset.csv to pharmaceutical_drugs_dataset.csv
User uploaded file "pharmaceutical_drugs_dataset.csv" with length 271648 bytes


In [ ]:
# loading the data from the csv file to apandas dataframe
medicines_data = pd.read_csv('pharmaceutical_drugs_dataset.csv')

In [ ]:
# printing the first 4 rows of the dataframe
medicines_data.head()

index  uniqueID         drugName                     condition  \
0      1    163740      Mirtazapine                    Depression   
1      2    206473       Mesalamine  Crohn's Disease, Maintenance   
2      3    159672          Bactrim       Urinary Tract Infection   
3      4     39293         Contrave                   Weight Loss   
4      5     97768  Cyclafem 1 / 35                 Birth Control   

                                              review  rating       date  \
0  I&#039;ve tried a few antidepressants over the...      10  28-Feb-12   
1  My son has Crohn&#039;s disease and has done v...       8  17-May-09   
2                        Quick reduction of symptoms       9  29-Sep-17   
3  Contrave combines drugs that were used for alc...       9  05-Mar-17   
4  I have been on this birth control for one cycl...       9  22-Oct-15   

   usefulCount  Unnamed: 8  Unnamed: 9  Unnamed: 10 Unnamed: 11  
0           22         NaN         NaN          NaN         NaN  
1           17         NaN         NaN          NaN         NaN  
2            3         NaN         NaN          NaN         NaN  
3           35         NaN         NaN          NaN         NaN  
4            4         NaN         NaN          NaN         NaN

In [ ]:
# number of rows and columns in the data frame

medicines_data.shape

(523, 12)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['condition']
print(selected_features)

['condition']


In [ ]:
# replacing the null values with null string

for feature in selected_features:
  medicines_data[feature] = medicines_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = medicines_data['condition']

In [ ]:
print(combined_features)

0                        Depression
1      Crohn's Disease, Maintenance
2           Urinary Tract Infection
3                       Weight Loss
4                     Birth Control
                   ...             
518                   Birth Control
519               Bowel Preparation
520                   Birth Control
521         Emergency Contraception
522                Diabetes, Type 2
Name: condition, Length: 523, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 57)	1.0
  (1, 121)	0.6089724577729185
  (1, 62)	0.5404805216104652
  (1, 52)	0.5805457358672876
  (2, 101)	0.4447632924960872
  (2, 203)	0.6333188824155016
  (2, 206)	0.6333188824155016
  (3, 119)	0.7071067811865476
  (3, 216)	0.7071067811865476
  (4, 49)	0.7071067811865475
  (4, 25)	0.7071067811865475
  (5, 111)	1.0
  (6, 49)	0.7071067811865475
  (6, 25)	0.7071067811865475
  (7, 163)	0.7071067811865475
  (7, 127)	0.7071067811865475
  (8, 218)	0.7453395614599931
  (8, 144)	0.6666850366722094
  (9, 49)	0.7071067811865475
  (9, 25)	0.7071067811865475
  (10, 78)	0.7071067811865475
  (10, 92)	0.7071067811865475
  (11, 219)	0.6063741006039737
  (11, 210)	0.6063741006039737
  (11, 101)	0.5144131610227757
  :	:
  (509, 118)	0.5773502691896257
  (509, 139)	0.5773502691896257
  (510, 24)	0.7725709410438673
  (510, 63)	0.6349284534926698
  (511, 68)	0.7071067811865475
  (511, 73)	0.7071067811865475
  (512, 181)	0.7849964087606219
  (512, 163)	0.619500313343687
  (513, 14)	0.687758536613707

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
print(similarity.shape)

(523, 523)


Getting the movie name from the user

In [ ]:
# getting the movie name from the user

medicine_name = input(' Enter your favourite medicine name : ')

 Enter your favourite medicine name : Contrave


In [ ]:
# creating a list with all the medicine names given in the dataset

list_of_all_titles = medicines_data['drugName'].tolist()
print(list_of_all_titles)

['Mirtazapine', 'Mesalamine', 'Bactrim', 'Contrave', 'Cyclafem 1 / 35', 'Zyclara', 'Copper', 'Amitriptyline', 'Methadone', 'Levora', 'Paroxetine', 'Miconazole', 'Belviq', 'Seroquel', 'Ambien', 'Nuvigil', 'Chantix', 'Microgestin Fe 1 / 20', 'Klonopin', 'Ciprofloxacin', 'Trazodone', 'EnteraGam', 'Aripiprazole', 'Cyclosporine', 'Oxybutynin', 'Lurasidone', 'Clonazepam', 'Ciclopirox', 'Sodium oxybate', 'Lamotrigine', 'Blisovi Fe 1 / 20', 'Ivermectin', 'Suprep Bowel Prep Kit', 'Movantik', 'Lorcaserin', 'Actos', 'Duloxetine', 'NuvaRing', 'Escitalopram', 'Tesamorelin', 'Campral', 'Gabapentin', 'Levonorgestrel', 'Aubra', 'Plan B One-Step', 'Ethinyl estradiol / etonogestrel', 'Microgestin Fe 1.5 / 30', 'Wellbutrin', 'Clonazepam', 'Benzoyl peroxide / clindamycin', 'Etonogestrel', 'Miconazole', 'Nitrofurantoin', 'Etonogestrel', 'Ortho Tri-Cyclen Lo', 'Tamsulosin', 'Tofacitinib', 'Cryselle', 'Amphetamine / dextroamphetamine', 'Clindamycin', 'Pramipexole', 'Skyla', 'Lastacaft', 'Effexor XR', 'Nifedi

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(medicine_name, list_of_all_titles)
print(find_close_match)

['Contrave', 'Contrave', 'Contrave']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Contrave


In [ ]:
# finding the index of the movie with title

index_of_the_movie = medicines_data[medicines_data.drugName == close_match]['index'].values[0]
print(index_of_the_movie)

4


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 1.0000000000000002), (5, 0.0), (6, 1.0000000000000002), (7, 0.0), (8, 0.0), (9, 1.0000000000000002), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 1.0000000000000002), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 1.0000000000000002), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 1.0000000000000002), (44, 0.0), (45, 1.0000000000000002), (46, 1.0000000000000002), (47, 0.0), (48, 0.0), (49, 0.0), (50, 1.0000000000000002), (51, 0.0), (52, 0.0), (53, 1.0000000000000002), (54, 1.0000000000000002), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 1.0000000000000002), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.0), (70, 1.0000000000000002), (71, 0.0), (72, 0.0), (73, 0.0), 

In [ ]:
len(similarity_score)

523

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(4, 1.0000000000000002), (6, 1.0000000000000002), (9, 1.0000000000000002), (30, 1.0000000000000002), (37, 1.0000000000000002), (43, 1.0000000000000002), (45, 1.0000000000000002), (46, 1.0000000000000002), (50, 1.0000000000000002), (53, 1.0000000000000002), (54, 1.0000000000000002), (61, 1.0000000000000002), (70, 1.0000000000000002), (74, 1.0000000000000002), (76, 1.0000000000000002), (85, 1.0000000000000002), (90, 1.0000000000000002), (92, 1.0000000000000002), (99, 1.0000000000000002), (101, 1.0000000000000002), (109, 1.0000000000000002), (110, 1.0000000000000002), (115, 1.0000000000000002), (116, 1.0000000000000002), (118, 1.0000000000000002), (121, 1.0000000000000002), (126, 1.0000000000000002), (127, 1.0000000000000002), (134, 1.0000000000000002), (139, 1.0000000000000002), (145, 1.0000000000000002), (147, 1.0000000000000002), (157, 1.0000000000000002), (167, 1.0000000000000002), (185, 1.0000000000000002), (191, 1.0000000000000002), (194, 1.0000000000000002), (196, 1.00000000000000

In [ ]:
# print the name of similar medicines based on the index

print('Medicines suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = medicines_data[medicines_data.index==index]['drugName'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Medicines suggested for you : 

1 . Cyclafem 1 / 35
2 . Copper
3 . Levora
4 . Blisovi Fe 1 / 20
5 . NuvaRing
6 . Aubra
7 . Ethinyl estradiol / etonogestrel
8 . Microgestin Fe 1.5 / 30
9 . Etonogestrel
10 . Etonogestrel
11 . Ortho Tri-Cyclen Lo
12 . Skyla
13 . Ethinyl estradiol / norethindrone
14 . ParaGard
15 . Ethinyl estradiol / levonorgestrel
16 . Aviane
17 . Implanon
18 . Levonorgestrel
19 . Levonorgestrel
20 . Ethinyl estradiol / norgestimate
21 . Lo Loestrin Fe
22 . Copper
23 . Yaz
24 . Copper
25 . Jolessa
26 . Nexplanon
27 . Lo Loestrin Fe
28 . Ethinyl estradiol / norgestimate
29 . Kariva


Movie Recommendation Sytem

In [ ]:
medicine_name = input(' Enter name of a medicine : ')

list_of_all_titles = medicines_data['drugName'].tolist()
find_close_match = difflib.get_close_matches(medicine_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = medicines_data[medicines_data.drugName == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print('Medicines suggested for you : \n')
i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = medicines_data[medicines_data.index==index]['drugName'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter name of a medicine : Contrave
Medicines suggested for you : 

1 . Cyclafem 1 / 35
2 . Levonorgestrel
3 . Levonorgestrel
4 . Levonorgestrel
5 . Levonorgestrel
6 . Levonorgestrel
7 . Levonorgestrel
8 . Levonorgestrel
9 . Levonorgestrel
10 . Etonogestrel
11 . Etonogestrel
12 . Etonogestrel
13 . Etonogestrel
14 . Etonogestrel
15 . Etonogestrel
16 . Etonogestrel
17 . Etonogestrel
18 . Etonogestrel
19 . Implanon
20 . Nexplanon
21 . Nexplanon
22 . Implanon
23 . Nexplanon
24 . Implanon
25 . Nexplanon
26 . Nexplanon
27 . Implanon
28 . Nexplanon
29 . Implanon
